name: Nfx.SDK.Core CI Pipeline

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    env:
      GITHUB_ENV: 
    steps:
      - uses: actions/checkout@v4
      - run: echo "SHORT=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
      - uses: microsoft/setup-msbuild@v1.1
      - uses: NuGet/setup-nuget@v2

      - name: Restore dependencies
        run: nuget restore Nfx.SDK.Core.sln

      - name: Build the solution
        run: msbuild Nfx.SDK.Core.sln /p:Configuration=Release /p:Outdir=Build

      - name: Attach Zip as build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Nfx.SDK.Core-${{ env.GITHUB_ENV }}
          path: Build