name: Nfx.SDK.Core CI Pipeline

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 4.7.1
    - name: Build 
      run: dotnet build -c Release Nfx.SDK.Core.sln -o Build
    - uses: actions/upload-artifact@v3.1.0
      with:
        name: Nfx.SDK.Core-${{ env.SEMVER }}
        path: Build