name: CI

on:
  push:
    branches:
      - "**"
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - "**"

jobs:
  calculate-version:
    name: Calculate Version
    runs-on: ubuntu-latest
    outputs:
      semVer: ${{ steps.gitversion.outputs.semVer }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.14
        with:
          versionSpec: "5.x"

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.14
        with:
          useConfigFile: true
          configFilePath: ./.github/version.yml

  build:
    runs-on: windows-latest
    needs: calculate-version
    env:
      SEMVER: ${{ needs.calculate-version.outputs.semVer }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.6

      - name: Restore dependencies
        run: nuget restore Nfx.SDK.Core.sln

      - name: Build the solution
        run: msbuild Nfx.SDK.Core.sln /p:Configuration=Release /p:Outdir=Build

      - name: Attach Zip as build artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: Nfx.SDK.Core-${{ env.SEMVER }}
          path: Build